definitions:
  pull_requests.CreatePRRequest:
    properties:
      author_id:
        type: string
      pull_request_id:
        type: string
      pull_request_name:
        type: string
    type: object
  pull_requests.CreatePRResponse:
    properties:
      pr:
        $ref: '#/definitions/pull_requests.PullRequestResponse'
    type: object
  pull_requests.MergePRRequest:
    properties:
      pull_request_id:
        type: string
    type: object
  pull_requests.MergePRResponse:
    properties:
      pr:
        $ref: '#/definitions/pull_requests.PullRequestResponse'
    type: object
  pull_requests.PullRequestResponse:
    properties:
      assigned_reviewers:
        items:
          type: string
        type: array
      author_id:
        type: string
      mergedAt:
        type: string
      pull_request_id:
        type: string
      pull_request_name:
        type: string
      replaced_by:
        type: string
      status:
        type: string
    type: object
  pull_requests.ReassignPRRequest:
    properties:
      old_reviewer_id:
        type: string
      pull_request_id:
        type: string
    type: object
  pull_requests.ReassignPRResponse:
    properties:
      pr:
        $ref: '#/definitions/pull_requests.PullRequestResponse'
    type: object
  response.ErrBodyResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      error:
        $ref: '#/definitions/response.ErrBodyResponse'
    type: object
  statistics.UserStatItemResponse:
    properties:
      assignments_count:
        type: integer
      user_id:
        type: string
      username:
        type: string
    type: object
  statistics.UserStatsResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/statistics.UserStatItemResponse'
        type: array
      limit:
        type: integer
      offset:
        type: integer
      total:
        type: integer
    type: object
  teams.Member:
    properties:
      is_active:
        type: boolean
      user_id:
        type: string
      username:
        type: string
    type: object
  teams.TeamAddRequest:
    properties:
      members:
        items:
          $ref: '#/definitions/teams.Member'
        type: array
      team_name:
        type: string
    type: object
  teams.TeamAddResponse:
    properties:
      team:
        $ref: '#/definitions/teams.TeamResponse'
    type: object
  teams.TeamResponse:
    properties:
      members:
        items:
          $ref: '#/definitions/teams.Member'
        type: array
      team_name:
        type: string
    type: object
  users.GetReviewResponse:
    properties:
      pull_requests:
        items:
          $ref: '#/definitions/users.PullRequestResponse'
        type: array
      user_id:
        type: string
    type: object
  users.PullRequestResponse:
    properties:
      author_id:
        type: string
      pull_request_id:
        type: string
      pull_request_name:
        type: string
      status:
        type: string
    type: object
  users.SetActiveRequest:
    properties:
      is_active:
        type: boolean
      user_id:
        type: string
    type: object
  users.SetIsActiveResponse:
    properties:
      user:
        $ref: '#/definitions/users.UserResponse'
    type: object
  users.UserResponse:
    properties:
      is_active:
        type: boolean
      team_name:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /pullRequest/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Параметры для создания PR
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pull_requests.CreatePRRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Созданный PR с назначенными ревьюверами
          schema:
            $ref: '#/definitions/pull_requests.CreatePRResponse'
        "400":
          description: INVALID_JSON
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: NOT_FOUND (author or team not found)
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: PR_EXISTS
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: INTERNAL_ERROR
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Создать PR и автоматически назначить до 2 ревьюверов из команды автора
      tags:
      - PullRequests
  /pullRequest/merge:
    post:
      consumes:
      - application/json
      parameters:
      - description: Идентификатор PR для merge
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pull_requests.MergePRRequest'
      produces:
      - application/json
      responses:
        "200":
          description: PR успешно помечен как MERGED
          schema:
            $ref: '#/definitions/pull_requests.MergePRResponse'
        "400":
          description: INVALID_JSON
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: NOT_FOUND
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: INTERNAL_ERROR
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Пометить PR как MERGED (идемпотентная операция)
      tags:
      - PullRequests
  /pullRequest/reassign:
    post:
      consumes:
      - application/json
      parameters:
      - description: PR и старый ревьювер
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/pull_requests.ReassignPRRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное переназначение ревьювера
          schema:
            $ref: '#/definitions/pull_requests.ReassignPRResponse'
        "400":
          description: INVALID_JSON
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: NOT_FOUND
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: PR_MERGED / NO_CANDIDATE / NOT_ASSIGNED
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: INTERNAL_ERROR
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Переназначить ревьювера на другого из его команды
      tags:
      - PullRequests
  /stats/users:
    get:
      consumes:
      - application/json
      description: Возвращает список пользователей и количество назначенных им PR
        с пагинацией.
      parameters:
      - description: Лимит выборки (по умолчанию 50, максимум 100)
        in: query
        name: limit
        type: integer
      - description: Смещение выборки (по умолчанию 0)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/statistics.UserStatsResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Статистика назначений по пользователям
      tags:
      - statistics
  /team/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Команда и её участники
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/teams.TeamAddRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Созданная/обновлённая команда
          schema:
            $ref: '#/definitions/teams.TeamAddResponse'
        "400":
          description: INVALID_JSON
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: NOT_FOUND
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "409":
          description: USERS_TEAM_EXISTS
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: INTERNAL_ERROR
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Создать команду с участниками (создаёт/обновляет пользователей)
      tags:
      - Teams
  /team/get:
    get:
      consumes:
      - application/json
      description: Возвращает состав команды по её имени.
      parameters:
      - description: Уникальное имя команды
        in: query
        name: team_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Команда и её участники
          schema:
            $ref: '#/definitions/teams.TeamResponse'
        "404":
          description: NOT_FOUND / TEAM_NOT_FOUND
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: INTERNAL_ERROR
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Получить команду с участниками
      tags:
      - Teams
  /users/getReview:
    get:
      consumes:
      - application/json
      description: Возвращает список PR'ов, в которых user_id указан как ревьювер
      parameters:
      - description: Идентификатор пользователя
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список PR'ов пользователя
          schema:
            $ref: '#/definitions/users.GetReviewResponse'
        "400":
          description: Некорректный запрос (нет user_id)
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Получить PR'ы, где пользователь назначен ревьювером
      tags:
      - Users
  /users/setIsActive:
    post:
      consumes:
      - application/json
      description: Принимает user_id и is_active, обновляет пользователя и возвращает
        его состояние
      parameters:
      - description: Тело запроса
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/users.SetActiveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Обновлённый пользователь
          schema:
            $ref: '#/definitions/users.SetIsActiveResponse'
        "400":
          description: Некорректный запрос
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Пользователь не найден
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Установить флаг активности пользователя
      tags:
      - Users
swagger: "2.0"
